[package]
name = "rust_profile_canister_backend_registry"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10.3"
ic-cdk = "0.19.0-beta.1"  
ic-cdk-macros = "0.19.0-beta.1"  
serde = { version = "1.0", features = ["derive"] }
